import { PropsWithChildren } from 'react';

import { Inter } from 'next/font/google';

import '@repo/ui/styles.css';

import './globals.css';

import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create turbo',
  title: 'Create Turborepo'
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
