import { PropsWithChildren } from 'react';

import '@repo/ui/styles.css';

import './globals.css';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  description: 'Generated by create turbo',
  title: 'Create Turborepo'
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
