import { PropsWithChildren } from 'react';

import '@repo/ui/styles.css';
import { ClickScrollPlugin, OverlayScrollbars } from 'overlayscrollbars';
import 'overlayscrollbars/overlayscrollbars.css';

import './globals.css';

import type { Metadata } from 'next';

OverlayScrollbars.plugin(ClickScrollPlugin);

export const metadata: Metadata = {
  description: 'Generated by create turbo',
  title: 'Create Turborepo'
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <script src="/jquery.min.js"></script>
      </head>
      <body>{children}</body>
    </html>
  );
}
